#!/bin/bash

REPO="snort3/snort3"
DOWNLOAD_URL=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | jq -r '.tarball_url')
# Or for zip archive, use: DOWNLOAD_URL=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | jq -r '.zipball_url')
curl -L $DOWNLOAD_URL -o ../tmp/snort3_latest_release.tar.gz
tar -zxvf ../tmp/snort3_latest_release.tar.gz -C ../tmp/snort3

